### ISSUE TITLE
Cannot install VS 2019, Autocad 2021

### ISSUE THREAD

**Issue by broose-goose** [ADN-DevTech/AutoCAD-Net-Wizards#8]
No matter what I do, I can't seem to get the .Net wizard installed.

I'm using VS 2019 and autocad 2021. I have literally every version of the .NET framework installed.

The installer says that it installed successfully, but the templates do not show up. I tried to install the objectarx template to see if anything would work, and was success installing those...

I took the READMEs advice, and ran it from the CMD prompt with admin privileges and output the log to a file. I find it has a bunch of errors like the following.

MSI (c) (A4:10) [20:48:30:502]: Note: 1: 2205 2:  3: Error 
MSI (c) (A4:10) [20:48:30:503]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2898 
Info 2898.For VSI_MS_Sans_Serif13.0_0_0 textstyle, the system created a 'MS Sans Serif' font, in 0 character set, of 13 pixels height.
MSI (c) (A4:10) [20:48:30:504]: Note: 1: 2205 2:  3: Error 
MSI (c) (A4:10) [20:48:30:505]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2826 
DEBUG: Error 2826:  Control BannerBmp on dialog WelcomeForm extends beyond the boundaries of the dialog to the right by 3 pixels
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2826. The arguments are: WelcomeForm, BannerBmp, to the right
MSI (c) (A4:10) [20:48:30:510]: Note: 1: 2205 2:  3: Error 
MSI (c) (A4:10) [20:48:30:511]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2898 
Info 2898.For VsdDefaultUIFont.524F4245_5254_5341_4C45_534153783400 textstyle, the system created a 'MS Sans Serif' font, in 0 character set, of 13 pixels height.
MSI (c) (A4:10) [20:48:30:512]: Note: 1: 2205 2:  3: Error 
MSI (c) (A4:10) [20:48:30:512]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2826 
DEBUG: Error 2826:  Control Line1 on dialog WelcomeForm extends beyond the boundaries of the dialog to the right by 3 pixels
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2826. The arguments are: WelcomeForm, Line1, to the right
MSI (c) (A4:10) [20:48:30:514]: Note: 1: 2205 2:  3: Error 
MSI (c) (A4:10) [20:48:30:515]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2826 
DEBUG: Error 2826:  Control Line2 on dialog WelcomeForm extends beyond the boundaries of the dialog to the right by 3 pixels
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2826. The arguments are: WelcomeForm, Line2, to the right
MSI (c) (A4:10) [20:48:30:516]: Note: 1: 2205 2:  3: Error 
MSI (c) (A4:10) [20:48:30:516]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2898 

I honestly think its a UI issue that is hosing everything up, but I really don't know...

Also, this is the output from the end

=== Logging stopped: 7/18/2020  21:19:43 ===
MSI (c) (E4:B0) [21:19:43:745]: Note: 1: 1707 
MSI (c) (E4:B0) [21:19:43:745]: Note: 1: 2205 2:  3: Error 
MSI (c) (E4:B0) [21:19:43:746]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1707 
MSI (c) (E4:B0) [21:19:43:746]: Note: 1: 2205 2:  3: Error 
MSI (c) (E4:B0) [21:19:43:746]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (E4:B0) [21:19:43:747]: Product: AutoCAD 2021 .NET Wizards -- Installation completed successfully.

MSI (c) (E4:B0) [21:19:43:747]: Windows Installer installed the product. Product Name: AutoCAD 2021 .NET Wizards. Product Version: 24.0.0. Product Language: 1033. Manufacturer: Autodesk. Installation success or error status: 0.

MSI (c) (E4:B0) [21:19:43:749]: Grabbed execution mutex.
MSI (c) (E4:B0) [21:19:43:749]: Cleaning up uninstalled install packages, if any exist
MSI (c) (E4:B0) [21:19:43:750]: MainEngineThread is returning 0
=== Verbose logging stopped: 7/18/2020  21:19:43 ===

**Comment by MadhukarMoogala** [comment]
Hi,
>The installer says that it installed successfully, but the templates do not show up. I tried to install the objectarx template to see if anything would work, and was success installing those...

Which version of VS 2019 you have ?, there is an [outstanding defect ](https://developercommunity.visualstudio.com/content/problem/973397/custom-wizard-vsz-and-template-directory-vsdir-are.html?childToView=995083#comment-995083)with Microsoft VS team, VS2019 v16.5.2, this has been fixed in VS 2019 v16.6

**Comment by broose-goose** [comment]
16.6.4, I will try downgrading to another 16.6 version and see if that fixes the issue.

I also find it strange the C++ works... I tried building the installer from source, but I'm not very familiar with the VS environment so I couldn't get it working

**Comment by guanrixing** [comment]
follow the listed steps:
1. Run AutoCADNetWizards.msi, it should say setup success:)
2. download the MSI Extractor，you can extract files from AutoCADNetWizards.msi
3. you can get two zip files, one is AutoCADNetWizards\Visual
Basic\Autodesk\AutoCAD 2021 VB plug‐in.zip, the other is  AutoCADNetWizards\Visual C#\Autodesk\ AutoCAD 2021 CSharp plug‐in.zip
4. copy these two template zip files to the visual studio template fold like this in my machine:D:\My Documents\Visual Studio 2019\Templates\ProjectTemplates 
5. Run the visual studio and new a project, in the templates select window, type "autocad" in the search text box, then you should find these two .net templates! good luck!

**Comment by guanrixing** [comment]
![Uploading 138D97EA-39B0-4F38-943E-05AC7D989D84.jpeg…]()
