### ISSUE TITLE
VS 2022 Installer

### ISSUE THREAD

**Issue by alex-d-richards** [ADN-DevTech/AutoCAD-Net-Wizards#9]
Hi, 

Would it be possible to get and installer that works with VS Community 2022. 

Thanks

**Comment by MadhukarMoogala** [comment]
We have not yet migrated, but I feel it should work without any change in the code base.

**Comment by benkoshy** [comment]
> We have not yet migrated, but I feel it should work without any change in the code base.

Looks like it's blocking / preventing installation, based on older versions of VS Community. Any ideas?

![image](https://user-images.githubusercontent.com/15097447/196819815-2c3b8244-507e-43c8-b11c-b55728898276.png)

**Comment by MadhukarMoogala** [comment]
This error is intentionally kept, see jere https://github.com/ADN-DevTech/AutoCAD-Net-Wizards/blob/36e98c43001b942eafde7f9dfa3ec7f923956792/AutoCADNetWizardsInstaller/AutoCADNetWizards.wxs#L36
You can uncomment to go away with this error.
